### ISSUE TITLE
How to fetch data on server side?

### ISSUE THREAD

**Issue by sh4hids** [trustworktech/create-react-ssr-app#12]
Thanks, @maxparelius  for such a nice project. It looks really promising. Currently, I am facing an issue regarding fetching data on the server-side (as there is no example).

In Next.js/After.js we have a method named `getInitialProps` to fetch data on the server-side. Does `CRSA` have anything like that?

**Comment by maxparelius** [comment]
@sh4hids yes you bring up a good point I decided not to implement a solution for this so as to keep the spirit of build config only and no implementation details. There are many ways to do what you are trying to do and it really depends on what you are using (Redux, Relay, Local State, etc). You could make something very similar to `getInitialProps` since you have access to all the node code. I can get a gist up later tonight I will get back to you and share how I would do it.

**Comment by sh4hids** [comment]
That would be great. Can you add an example folder with basic implementation like next.js?

**Comment by jleei** [comment]
Please add redux example.
