### ISSUE TITLE
Proxy in package.json

### ISSUE THREAD

**Issue by vincezun** [trustworktech/create-react-ssr-app#6]
Adding proxy in package.json is not working but if I add it directly in axios.get() it is working.
This is what I get when it is from the proxy in package.json
![image](https://user-images.githubusercontent.com/49867576/56564056-d0ff1080-65df-11e9-9ec9-06447d1a930d.png)

And when I npm start I'm getting this DeprecationWarning
![image](https://user-images.githubusercontent.com/49867576/56564107-f25ffc80-65df-11e9-8292-bde68549a3cf.png)

Already tried proxy in package.json in create-react-app and it is working. 
![image](https://user-images.githubusercontent.com/49867576/56564041-c9d80280-65df-11e9-94e0-cbceba25b92b.png)

**Comment by Butonix** [comment]
> Adding proxy in package.json is not working but if I add it directly in axios.get() it is working.
> This is what I get when it is from the proxy in package.json
> ![image](https://user-images.githubusercontent.com/49867576/56564056-d0ff1080-65df-11e9-9ec9-06447d1a930d.png)
> 
> And when I npm start I'm getting this DeprecationWarning
> ![image](https://user-images.githubusercontent.com/49867576/56564107-f25ffc80-65df-11e9-8292-bde68549a3cf.png)
> 
> Already tried proxy in package.json in create-react-app and it is working.
> ![image](https://user-images.githubusercontent.com/49867576/56564041-c9d80280-65df-11e9-94e0-cbceba25b92b.png)

I, too, wrote about this author, but he ignored me! There is no support, so it is better not to use this repository!

**Comment by vincezun** [comment]
Maybe they are busy, so we wait...

**Comment by Butonix** [comment]
> Maybe they are busy, so we wait...

No, he just silently closed my question.
Try razzle he's a lot better

**Comment by vinzun** [comment]
jaredpalmer?

**Comment by maxparelius** [comment]
@vinzun @Butonix proxy is much different behavior with ssr so it does not work the same as in cra. I am not sure why you need a proxy. Any request from the browser goes to the rendering server by default. If you want it to go somewhere else just use the full url. If you really want a proxy you can implement it at the node level in the rendering server.

**Comment by vincezun** [comment]
Thanks for the info. I am new to this, learning new stuffs.  I also tried it with different framework and noticed that it's not working with any ssr. I'm trying to research about this and spent a lot of time. Thanks again bro!

**Comment by maxparelius** [comment]
@vinzun what does your stack look like? Generally a proxy is useful when you want some route (`e.g. /my_profile`) to go somewhere else other than the server that served the app. With CRA its useful since the app is served by a webpack dev server and api requests are not handled by that server. So a proxy allows to send api requests to the api server. In my stack I generally use a single node server just for rendering. Create React SSR App comes with this server configured. I then use a different server (rails, node, go, or something else) to handle API requests. In my client code I use the full url for API requests (e.g. `http://localhost:3000/my_profile` rather than `/my_profile`) so which makes proxy unecessary.

**Comment by vincezun** [comment]
Im creating a website using React and WP Rest Api, it just got me thinking about how headless cms  will be called when it comes to production.
